### PR TITLE
Fix: Disable loadtest on test/temp rses

### PR DESCRIPTION
**Pull request by guyzsarun**
Fix: https://github.com/dmwm/CMSRucio/pull/639

Update loadtest from SITECONF storage.json on  rse `cms_type: real` only

### CODE REVIEW

**Comment by dynamic-entropy** [comment]
Hello! 
Yes, I noticed this, from rule approved messages. However, is it not good to have the loadtests on the test rses?
For temp, I agree.

**Comment by dynamic-entropy** [comment]
Thankyou so much for the PR though.

**Comment by guyzsarun** [comment]
it is crashing the loadtest service.
From my understanding, the test rse also points to the same endpoint as the original just on different path?

> Hello! Yes, I noticed this, from rule approved messages. However, is it not good to have the loadtests on the test rses? For temp, I agree.

**Comment by dynamic-entropy** [comment]
Ok, thankyou.

**Comment by dynamic-entropy** [comment]
We can let it be as is for now. (I don't want to touch loadtests, until someone takes to refactoring and documentung it all).

**Comment by dynamic-entropy** [comment]
I deleted the ones for test (and temp) rses too actually. When I merged this.

**Pull request merged**
