### PR TITLE
Create loadtest-docker-image.yml 

### LINKED ISSUE #496: Add Actions workflow to build and push images to harbour
I will start with images that we build from scratch. 

Then we need to think about rucio images without patches.

FYI @ericvaandering

### PR DESCRIPTION
**Pull request by dynamic-entropy**
Fix #496

### CODE REVIEW

**Comment by dynamic-entropy** [comment]
Hi @ericvaandering 

To give some context. 
So, because we have so many docker files in the same repo, I did not want to trigger builds every time there is a push in the repo. 
Secondly, there was an issue with how to choose various image tags for each file etc. 

So at the moment, I used the tag `loadtest-v*` as the trigger for the workflow: this only builds an image for loadtest-client. 

If you like the approach we can simply for workflows for other images. 
And building new images will then be just a matter of pushing a relevant tag.

**Comment by ericvaandering** [comment]
I'd prefer the git tags to be loadtest-x.y.z (no v for version) and then the harbor tags must be just x.y.z.

Can you do that? Otherwise I completely agree, we do not want to build images on every push to main.

Also we need to do something to keep the project cleaned up. Often now I have trouble pushing an image because we are over quota.

**Comment by dynamic-entropy** [comment]
Done. 
A tag of `loadtest-x.y.z` will create an image with tag `image-name:x.y.z`.

About cleaning up the project, let me see what can be done, do you have any suggestions?

**Comment by ericvaandering** [comment]
Looks good. You can merge it

**Pull request merged**
