### PR TITLE
Loadtest implementation

### PR DESCRIPTION
**Pull request by nsmith-**
The `run.sh` is for testing, while a more appropriate kubernetes pod config would have something like
```
--source_rse_expression "rse_type=disk&cms_type=real&tier<3" --dest_rse_expression "rse_type=disk&cms_type=real&tier<3"
```
as the arguments

### CODE REVIEW

**Comment by ericvaandering** [comment]
This seems to have a lot of other work attached to it. I'll cherry-pick out the load test part and merge that.

Of course we should get the rest in too in some other PRs.

**Comment by nsmith-** [comment]
The others are just small changes to DM ops utilities, I wouldn't worry about it

**Comment by nsmith-** [comment]
So you copied the file in rather than merge this? Should I close?

**Comment by ericvaandering** [comment]
I cherry picked the right parts.

**Pull request closed without merging**
