### PR TITLE
Add replica recoverer daemon config in the policy package

### PR DESCRIPTION
**Pull request by haozturk**
replica recoveror daemon requires a json file for its configuration [1]. I don't know what's the best way to get this file into the image. Since policy package is already copied into the image and it's the place for cms specific policy, I've put it there. @ericvaandering @dynamic-entropy if you think that this is not the right place, I can put it elsewhere in the repo and update the dockerfile to copy it specifically. Please let me know

[1] https://github.com/rucio/rucio/blob/730e0f555a8496bf2ad7aef7d84ed699dfcb4466/lib/rucio/daemons/replicarecoverer/suspicious_replica_recoverer.py#L586

### CODE REVIEW

**Comment by ericvaandering** [comment]
In general I'd prefer this do be done in flux since it's configuration. But the way to do that which is supported is secretmounts https://github.com/rucio/helm-charts/blob/ca88fa01f8e3d30fb18ddeb4b4719e4fee59a3f5/charts/rucio-daemons/values.yaml#L471 which would require another secret. I don't see another way in the flux/helm system we have set up. 

As a matter of principle I would prefer a configmap which was mounted.

**Comment by haozturk** [comment]
I see, I agree it's better to keep the configuration in flux. It's also true that doing this via secrets isn't ideal. If you think secret way is better, I can do it that way.

> As a matter of principle I would prefer a configmap which was mounted.

This would have been ideal. The template that comes from upstream [1] has to be updated to allow that, right? I might be missing some details.

[1] https://github.com/rucio/helm-charts/blob/ca88fa01f8e3d30fb18ddeb4b4719e4fee59a3f5/charts/rucio-daemons/templates/replica-recoverer-deployment.yaml#L113

**Comment by ericvaandering** [comment]
You are not missing anything. If you don't see a way to do it with the existing helm chart, I think we just merge this.

**Comment by haozturk** [comment]
I didn't try, but I think it's possible to do by using the secretMounts and making this config a secret. If you think that's better, I can try it out

**Comment by haozturk** [comment]
Mounting this config as a secret works: 
https://github.com/dmwm/rucio-flux/pull/297
https://github.com/dmwm/rucio-flux/pull/298
```
{"log": {"logger": "root", "level": "INFO"}, "@timestamp": "2024-06-11T02:00:17.597Z", "process": {"pid": 9}, "message": "[2/4]: JSON file has been opened.", "error": {"type": null, "message": null, "stack_trace": null}}
```
Closing this one

**Pull request closed without merging**
